services:
  web:
    build: 
      context: ./ #not the best practise?
      dockerfile: ./Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env-variables.env
    ports:
      - 63385:80
      - 44319:443
  db:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="aaaa" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'szpek'
      MYSQL_ROOT_PASSWORD: 'aaaa'
    ports:
      - 3307:3306
volumes:
  db-data:
       
