on: 
  release:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "AAAA: ${{ github.event.release.tag_name }}"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: test
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: test3
      run: echo "$eee"
    - name: Publish 
      env:
          release-version: ${{ github.event.release.tag_name }}
      run: dotnet publish Api -p:Version="$release-version" -c Release -o output 
    - name: Export App
      uses: actions/upload-artifact@v3
      with:
        name: szpek-app-v- ${{ github.event.release.tag_name }}
        path: output